name: summarization_tf
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.6.8
  - nltk=3.4
  - astor=0.7.1
  - pandas=0.25.1
  - numpy==1.16.2
#   - matplotlib=3.0.2
#   - keras=2.2.4
  - ipython=7.2.0
#   - faiss-cpu=1.5.3
#   - gitpython=2.1.11
  - seaborn=0.9.0
#   - fuzzywuzzy=0.17.0
  - more-itertools=5.0.0
#   - flask-cors=3.0.7
#   - airflow=1.10.3
#   - pytorch=1.1.0
#   - psycopg2=2.8.3
#   - tensorflow-hub=0.6.0
  - pip:
    - prefetch-generator==1.0.0
    - pathos==0.2.2.1
    - tensorflow==1.12.0
    - gensim==3.8.1
    - ktext==0.34
    - torch==0.3.1
    - torchtext==0.2.3
    - torchvision==0.2.0
    - APScheduler==3.6.3

